/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan_Menu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.New_ConnectDB;
import java.text.NumberFormat;

/**
 *
 * @author user
 */
public class Dashboard_Member extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();
    private DefaultTableModel tabmode;
    
    protected void dataTable() {
        Object[]baris = {"Tanggal","Jenis Sampah","Berat Sampah","Verifikator"};
        tabmode = new DefaultTableModel(null, baris);
        tabelout.setModel(tabmode);
        String sql = "select Tanggal,Jenis_Sampah,Berat_Sampah,Verifikator from sampah where No_Handphone='"+jlnohp.getText()+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stanggal = hasil.getString("Tanggal");
                String sjenis_sampah  = hasil.getString("Berat_Sampah");
                String  sberat_sampah = hasil.getString("Jenis_Sampah");
                String sverif = hasil.getString("Verifikator");
                String[] data = {stanggal,sjenis_sampah,sberat_sampah,sverif};
                tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }
    
    protected void Cek_Saldo() {
        try {
            String sql = "select Saldo_Total from member where No_Handphone = '" + jlnohp.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_saldo = hasil.getString("Saldo_Total");
                //editan baru
                tumbal.setText(stotal_saldo);
                int total = Integer.parseInt(tumbal.getText());
                NumberFormat nf = NumberFormat.getInstance();
                jlsaldo_member.setText(""+nf.format(total));
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Total Saldo gagal diperbarui" +e);
        }
    }
    
    protected void Saldo_Regist() {
        try {
            String sql = "update member set Saldo_Total=0 where No_Handphone='"+jlnohp.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.executeUpdate();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Total Saldo gagal diperbarui" +e);
        }
    }
    
    protected void reset() {
            try {
                String sql = "delete from sampah where Rupiah_Sampah !='0' && No_Handphone='"+jlnohp.getText()+"'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,
                        "Data gagal direset" +e);
            }
    }
    
    
    protected void kondisi() {
        
            int a = Integer.parseInt(tumbal.getText());
                if (a > 500000000){
                    int scair = a-50000;
                    NumberFormat nf = NumberFormat.getInstance();
                    jlcair.setText(""+nf.format(scair));
                    cair.setEnabled(true);
                }else {
                    cair.setEnabled(false);
                }
            
    }
    
    
    
    
    /**
     * Creates new form Dashboard_Member
     */
    public Dashboard_Member() {
        initComponents();
        setTanggal();
        setLocationRelativeTo(this);
        tfnama.setEnabled(false);
        tfnohp.setEnabled(false);
        tfsaldo.setEnabled(false);
        tftanggal.setEnabled(false);
        tfberita.setEnabled(false);
        jlberita.setVisible(true);
        tfcair.setEnabled(false);
        
        
        
    }
    public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jltanggal.setText(kal.format(skrg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tumbal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbnama_bank = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jlsaldo_member = new javax.swing.JLabel();
        tfsaldo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelout = new javax.swing.JTable();
        jlnama = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jlnohp = new javax.swing.JLabel();
        tfnohp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfno_rec = new javax.swing.JTextField();
        jltanggal = new javax.swing.JLabel();
        tftanggal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jlberita = new javax.swing.JLabel();
        tfberita = new javax.swing.JTextField();
        jlcair = new javax.swing.JLabel();
        tfcair = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daftar Riwayat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 420, 120, 19);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 50, 19);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No Handphone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 213, 110, 19);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Bank");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 256, 90, 19);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Rekening");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 295, 100, 19);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("Pencairan bulan ini");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 340, 200, 21);

        cbnama_bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank Indonesia (BS)", "Bank Negara Indonesia (BNI)", "Bank Rakyat Indonesia (BRI)", "Bank Mandiri", "Bank Tabungan Negara (BTN)", "Bank Central Asia (BCA)" }));
        cbnama_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnama_bankActionPerformed(evt);
            }
        });
        jPanel1.add(cbnama_bank);
        cbnama_bank.setBounds(240, 250, 220, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Rp");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 370, 26, 26);

        jlsaldo_member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlsaldo_member.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlsaldo_memberAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jlsaldo_member);
        jlsaldo_member.setBounds(120, 370, 140, 30);
        jPanel1.add(tfsaldo);
        tfsaldo.setBounds(110, 370, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 520, 73, 30);

        cair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cair.setText("Cairkan");
        cair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cairActionPerformed(evt);
            }
        });
        jPanel1.add(cair);
        cair.setBounds(490, 370, 80, 30);

        tabelout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Jenis Sampah", "Berat Sampah", "Verifikator"
            }
        ));
        tabelout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabeloutKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelout);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 450, 440, 110);
        jPanel1.add(jlnama);
        jlnama.setBounds(250, 170, 180, 30);

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        jPanel1.add(tfnama);
        tfnama.setBounds(240, 170, 180, 30);
        jPanel1.add(jlnohp);
        jlnohp.setBounds(250, 210, 180, 30);

        tfnohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnohpActionPerformed(evt);
            }
        });
        jPanel1.add(tfnohp);
        tfnohp.setBounds(240, 210, 180, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Pemberitahuan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 585, 140, 21);
        jPanel1.add(tfno_rec);
        tfno_rec.setBounds(240, 290, 270, 30);
        jPanel1.add(jltanggal);
        jltanggal.setBounds(810, 150, 90, 30);
        jPanel1.add(tftanggal);
        tftanggal.setBounds(800, 150, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Cek Riwayat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 450, 110, 30);

        jlberita.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jlberita.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlberitaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jlberita);
        jlberita.setBounds(170, 580, 710, 30);
        jPanel1.add(tfberita);
        tfberita.setBounds(160, 580, 720, 30);

        jlcair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jlcair);
        jlcair.setBounds(360, 370, 120, 30);
        jPanel1.add(tfcair);
        tfcair.setBounds(350, 370, 130, 30);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setText("Saldo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 340, 60, 21);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("Rp");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 370, 26, 26);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 290, 80, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_Menu/FormDashboard.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 968, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbnama_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnama_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnama_bankActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new FormLoginUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfnamaActionPerformed

    private void tfnohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnohpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfnohpActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                kondisi();
                Cek_Saldo();
            
        dataTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabeloutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabeloutKeyPressed
        // TODO add your handling code here:
        int bar = tabelout.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
       
    }//GEN-LAST:event_tabeloutKeyPressed

    private void cairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cairActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,
                "Anda yakin ingin mencairkan saldo ?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            try {
               
                kondisi();
                String sql = "insert into result (Tanggal,No_Handphone,Nama,Nama_Bank,No_Rek,Pencairan,Status) value (?,?,?,?,?,?,'Sukses');";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, jltanggal.getText());
                stat.setString(2, jlnohp.getText());
                stat.setString(3, jlnama.getText());
                stat.setString(4, (String) cbnama_bank.getSelectedItem());
                stat.setString(5, tfno_rec.getText());
                stat.setString(6, jlcair.getText());
                stat.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(null,"Dana "+jlnama.getText()+"\nSebesar Rp "+jlcair.getText()+"\nBerhasil dicairkan",
                    "Konfirmasi",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                reset();
                Saldo_Regist();
                dispose();
                new FormLoginUtama().setVisible(true);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,
                        "Dana gagal dicairkan" +e);
            }  
        }
    }//GEN-LAST:event_cairActionPerformed

    private void jlsaldo_memberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlsaldo_memberAncestorAdded
        // TODO add your handling code here:
        //editan terbaru
        /*String sql = "select sum(Total_Saldo) from member where No_Handphone = '"+jlnohp.getText()+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                    jlsaldo_member.setText(hasil.getString("Total_Saldo"));
            }
        }catch (Exception e) {
            
        }
        */
    }//GEN-LAST:event_jlsaldo_memberAncestorAdded

    private void jlberitaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlberitaAncestorAdded
        // TODO add your handling code here:
        try {
            String sql = "select Berita from admin ";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sberita = hasil.getString("Berita");
                jlberita.setText(sberita);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jlberitaAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update member set Nama_Bank=?,"
                    + "No_Rec=? "
                    + "where No_Handphone='"+jlnohp.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, (String) cbnama_bank.getSelectedItem());
            stat.setString(2, tfno_rec.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    "Data berhasil di ubah");
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Data gagal diubah" +e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cair;
    public static javax.swing.JComboBox<String> cbnama_bank;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel jlberita;
    private javax.swing.JLabel jlcair;
    public static javax.swing.JLabel jlnama;
    public static javax.swing.JLabel jlnohp;
    public static javax.swing.JLabel jlsaldo_member;
    private javax.swing.JLabel jltanggal;
    private javax.swing.JTable tabelout;
    private javax.swing.JTextField tfberita;
    private javax.swing.JTextField tfcair;
    private javax.swing.JTextField tfnama;
    public static javax.swing.JTextField tfno_rec;
    private javax.swing.JTextField tfnohp;
    private javax.swing.JTextField tfsaldo;
    private javax.swing.JTextField tftanggal;
    private javax.swing.JLabel tumbal;
    // End of variables declaration//GEN-END:variables
}
