/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan_Menu;

import koneksi.New_ConnectDB;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;


/**
 *
 * @author user
 */
public class Dashboard_Brokers extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();
    private DefaultTableModel tabmode;
    
    protected void dataTable() {
        Object[]baris = {"Tanggal","No Handphone","Jenis Sampah","Berat Sampah","Verifikator"};
        tabmode = new DefaultTableModel(null, baris);
        tabelout.setModel(tabmode);
        String sql = "select Tanggal,No_Handphone,Jenis_Sampah,Berat_Sampah,Verifikator from sampah where No_Handphone='"+tfregist_nohp.getText()+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stanggal = hasil.getString("Tanggal");
                String no_hp = hasil.getString("No_Handphone");
                String jenis_sampah = hasil.getString("Jenis_Sampah");
                String berat_sampah = hasil.getString("Berat_Sampah");
                String verif = hasil.getString("Verifikator");
                String[] data = {stanggal,no_hp, jenis_sampah, berat_sampah, verif};
                tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }
    
    
    /**
     * Creates new form Dashboard_Brokers
     */
    public Dashboard_Brokers() {
        initComponents();
        setLocationRelativeTo(this);
        setTanggal();
        tftanggal.setEnabled(false);
        tfberita.setEnabled(false);
        tfsaldo.setEnabled(false);
        tfregist_nohp.requestFocus();
        tfnama.setEnabled(false);
        
    }
    
    protected void kosong() {
        tfregist_nohp.setText("");
        tfberat_sampah.setText("");
        tfbrokers_user.setText("");
        tfbrokers_nama.setText("");
        tfregist_nohp.setText("");
        pfbrokers_pass.setText("");
        tbrokers_alamat.setText("");
        pfpin.setText("");
        jlnama.setText("");
        
    }
    public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jltanggal.setText(kal.format(skrg));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfregist_nohp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbjenis_sampah = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfberat_sampah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btsubmit_broker = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbverif = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        logo_regist = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelout = new javax.swing.JTable();
        jltanggal = new javax.swing.JLabel();
        tftanggal = new javax.swing.JTextField();
        harga_besi = new javax.swing.JLabel();
        harga_tembaga = new javax.swing.JLabel();
        harga_plastic = new javax.swing.JLabel();
        harga_kaca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfberita = new javax.swing.JTextField();
        jlsaldo = new javax.swing.JLabel();
        tfsaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pfpin = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlnama = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        tfbrokers_user = new javax.swing.JTextField();
        tfbrokers_nama = new javax.swing.JTextField();
        pfbrokers_pass = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbrokers_alamat = new javax.swing.JTextArea();
        jlsaldo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 240, 120, 19);

        tfregist_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfregist_nohpActionPerformed(evt);
            }
        });
        tfregist_nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfregist_nohpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfregist_nohpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfregist_nohpKeyTyped(evt);
            }
        });
        jPanel1.add(tfregist_nohp);
        tfregist_nohp.setBounds(510, 200, 180, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Sampah");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 280, 120, 19);

        cbjenis_sampah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sampah Besi", "Sampah Tembaga", "Sampah Plastic", "Sampah Kaca" }));
        cbjenis_sampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenis_sampahActionPerformed(evt);
            }
        });
        jPanel1.add(cbjenis_sampah);
        cbjenis_sampah.setBounds(540, 280, 150, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berat Sampah (KG)");
        jLabel5.setAutoscrolls(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 320, 170, 19);

        tfberat_sampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfberat_sampahMouseClicked(evt);
            }
        });
        jPanel1.add(tfberat_sampah);
        tfberat_sampah.setBounds(540, 320, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Verifikator");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 360, 100, 19);

        btsubmit_broker.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btsubmit_broker.setText("Submit");
        btsubmit_broker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubmit_brokerActionPerformed(evt);
            }
        });
        jPanel1.add(btsubmit_broker);
        btsubmit_broker.setBounds(420, 420, 73, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 420, 73, 30);

        cbverif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muammar Nasution", "Mudrika Latif", "Nio Bramasta" }));
        jPanel1.add(cbverif);
        cbverif.setBounds(540, 360, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Pemberitahuan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 582, 140, 21);

        logo_regist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_Menu/register.png"))); // NOI18N
        jPanel1.add(logo_regist);
        logo_regist.setBounds(80, 190, 250, 250);

        tabelout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "No Handphone", "Jenis Sampah", "Berat Sampah", "Verifikator"
            }
        ));
        tabelout.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabeloutAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabeloutKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelout);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(260, 470, 452, 100);
        jPanel1.add(jltanggal);
        jltanggal.setBounds(810, 150, 90, 30);
        jPanel1.add(tftanggal);
        tftanggal.setBounds(800, 150, 90, 30);

        harga_besi.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        harga_besi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                harga_besiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(harga_besi);
        harga_besi.setBounds(260, 580, 80, 30);

        harga_tembaga.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        harga_tembaga.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                harga_tembagaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(harga_tembaga);
        harga_tembaga.setBounds(460, 580, 80, 30);

        harga_plastic.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        harga_plastic.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                harga_plasticAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(harga_plastic);
        harga_plastic.setBounds(640, 580, 80, 30);

        harga_kaca.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        harga_kaca.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                harga_kacaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(harga_kaca);
        harga_kaca.setBounds(810, 580, 80, 30);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Harga Besi :                                 Harga Tembaga :                                Harga Plastic :                                   Harga Kaca :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 580, 710, 30);

        tfberita.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfberita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfberitaActionPerformed(evt);
            }
        });
        jPanel1.add(tfberita);
        tfberita.setBounds(180, 580, 710, 30);

        jlsaldo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jPanel1.add(jlsaldo);
        jlsaldo.setBounds(790, 420, 100, 30);

        tfsaldo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jPanel1.add(tfsaldo);
        tfsaldo.setBounds(770, 420, 120, 30);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setText("Rp.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(740, 420, 30, 30);

        pfpin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pfpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfpinActionPerformed(evt);
            }
        });
        jPanel1.add(pfpin);
        pfpin.setBounds(800, 70, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel7.setText("PIN");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(770, 78, 34, 14);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No Handphone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 205, 120, 19);

        jlnama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlnamaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jlnama);
        jlnama.setBounds(530, 240, 160, 30);

        tfnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnamaKeyTyped(evt);
            }
        });
        jPanel1.add(tfnama);
        tfnama.setBounds(510, 240, 180, 30);

        background.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_Menu/FormDashboard.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 970, 622);
        jPanel1.add(tfbrokers_user);
        tfbrokers_user.setBounds(530, 230, 270, 30);
        jPanel1.add(tfbrokers_nama);
        tfbrokers_nama.setBounds(530, 270, 270, 30);
        jPanel1.add(pfbrokers_pass);
        pfbrokers_pass.setBounds(530, 350, 270, 30);

        tbrokers_alamat.setColumns(20);
        tbrokers_alamat.setRows(5);
        jScrollPane1.setViewportView(tbrokers_alamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(530, 390, 270, 110);
        jPanel1.add(jlsaldo2);
        jlsaldo2.setBounds(600, 160, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbjenis_sampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenis_sampahActionPerformed
        // TODO add your handling code here: 
        
        
    }//GEN-LAST:event_cbjenis_sampahActionPerformed

    private void btsubmit_brokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubmit_brokerActionPerformed
        // TODO add your handling code here:
        //String sql = "insert into member (Tanggal,No_Handphone,Jenis_Sampah,Berat_Sampah,Verifikator,Username,Nama,Password,Alamat,JS_Besi,JS_Tembaga,JS_Plastic,JS_Kaca,Harga_Besi,Harga_Tembaga,Harga_Plastic,Harga_Kaca,No_Rec,Nama_Bank,Saldo_Total) values (?,?,?,?,?,0,0,0,0,0,0,0,0,7000,60000,4000,5000,0,0,0);";
        try {
            String sql = "insert into sampah (Tanggal,No_Handphone,Jenis_Sampah,Berat_Sampah,Verifikator,Rupiah_Sampah) value (?,?,?,?,?,?);";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, jltanggal.getText());
            stat.setString(2, tfregist_nohp.getText());
            stat.setString(3, (String) cbjenis_sampah.getSelectedItem());
            stat.setString(4, tfberat_sampah.getText());
            stat.setString(5, (String) cbverif.getSelectedItem());
            if (cbjenis_sampah.getSelectedItem()=="Sampah Besi") {
                //stat.setString(7, (String) tfberat_sampah.getText());
                int a = Integer.parseInt(tfberat_sampah.getText());
                int b = Integer.parseInt(harga_besi.getText());
                int total_dibroker = a * b;
                NumberFormat nf = NumberFormat.getInstance();
                jlsaldo.setText("" +nf.format(total_dibroker));
                jlsaldo2.setText(""+total_dibroker);
                //Lanjutan edit marrr
                /*String saldo_db = conn.getString("Total_Saldo");
                Dashboard_Member z= new Dashboard_Member();
                int saldo_sementara = Integer.parseInt(jlsaldo.getText());
                int saldo_database = Integer.parseInt(saldo_db);
                int total_saldo = saldo_database+saldo_sementara;
                String fix = Integer.toString(total_saldo);
                z.jlsaldo_member.setText(fix);
                */
                //bates edit mar
                stat.setString(6,jlsaldo2.getText());
            }else if (cbjenis_sampah.getSelectedItem()=="Sampah Tembaga") {
                //stat.setString(8, (String) tfberat_sampah.getText());
                int a = Integer.parseInt(tfberat_sampah.getText());
                int b = Integer.parseInt(harga_tembaga.getText());
                int total_dibroker = a * b;
                NumberFormat nf = NumberFormat.getInstance();
                jlsaldo.setText("" +nf.format(total_dibroker));
                jlsaldo2.setText(""+total_dibroker);
                stat.setString(6,jlsaldo2.getText());
            } else if (cbjenis_sampah.getSelectedItem()=="Sampah Plastic") {
                //stat.setString(9, (String) tfberat_sampah.getText());
                int a = Integer.parseInt(tfberat_sampah.getText());
                int b = Integer.parseInt(harga_plastic.getText());
                int total_dibroker = a * b;
                NumberFormat nf = NumberFormat.getInstance();
                jlsaldo.setText("" +nf.format(total_dibroker));
                jlsaldo2.setText(""+total_dibroker);
                stat.setString(6,jlsaldo2.getText());
            }else {
                //stat.setString(10, (String) tfberat_sampah.getText());
                int a = Integer.parseInt(tfberat_sampah.getText());
                int b = Integer.parseInt(harga_kaca.getText());
                int total_dibroker = a * b;
                NumberFormat nf = NumberFormat.getInstance();
                jlsaldo.setText("" +nf.format(total_dibroker));
                jlsaldo2.setText(""+total_dibroker);
                stat.setString(6,jlsaldo2.getText());
                
            }
            
            
            //stat.setString(2, tfbrokers_user.getText());
            //stat.setString(3, tfbrokers_nama.getText());
            //stat.setString(4, tfregist_nohp.getText());
            //stat.setString(5, pfbrokers_pass.getText());
            //stat.setString(6, tbrokers_alamat.getText());
            //stat.setString(7, (String) cbjenis_sampah.getSelectedItem());
            //stat.setString(8,tfberat_sampah.getText());
            //stat.setString(9, (String) cbverif.getSelectedItem());
            /*stat.setString(10, jltanggal.getText());
            stat.setString(11, tfbrokers_user.getText());
            stat.setString(12, tfbrokers_nama.getText());
            stat.setString(13, tfregist_nohp.getText());
            stat.setString(14, pfbrokers_pass.getText());
            stat.setString(15, tbrokers_alamat.getText());
            stat.setString(16, jltanggal.getText());
            stat.setString(17, tfbrokers_user.getText());
            stat.setString(18, tfbrokers_nama.getText());
            stat.setString(19, tfregist_nohp.getText());
            stat.setString(20, pfbrokers_pass.getText());
            */
           
            
            stat.executeUpdate();
            dataTable();
            JOptionPane.showMessageDialog(null,
                    "Data berhasil disimpan");
            kosong();
            tfregist_nohp.requestFocus();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Data gagal disimpan" +e);
        }
        
    }//GEN-LAST:event_btsubmit_brokerActionPerformed

    private void tfberat_sampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfberat_sampahMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfberat_sampahMouseClicked

    private void tabeloutAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabeloutAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabeloutAncestorAdded

    private void tabeloutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabeloutKeyPressed
        // TODO add your handling code here:
        /*int bar = tabelout.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
       
        switch (b) {
            case "Sampah Besi":
                cbjenis_sampah.setSelectedIndex(0);
                break;
            case "Sampah Tembaga":
                cbjenis_sampah.setSelectedIndex(1);
                break;
            case "Sampah Plastic":
                cbjenis_sampah.setSelectedIndex(2);
                break;
            case "Sampah Kaca":
                cbjenis_sampah.setSelectedIndex(3);
                break;
        }
        switch (d) {
            case "Muammar Nasution":
                cbverif.setSelectedIndex(0);
                break;
            case "Mudrika Latif":
                cbverif.setSelectedIndex(1);
                break;
            case "Nio Bramasta":
                cbverif.setSelectedIndex(2);
                break;
            
        }
        tfregist_nohp.setText(a);
        tfberat_sampah.setText(c);
        */
        
    }//GEN-LAST:event_tabeloutKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new FormLoginUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfberitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfberitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfberitaActionPerformed

    private void pfpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpinActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "select * from admin where Pin = '" + pfpin.getText() + "'";
            Statement stat = conn.createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                JOptionPane.showMessageDialog(null, "Akses Dashboard Admin!");
                dispose();
                String sharga_besi = rsLogin.getString("Harga_Besi");
                String sharga_tembaga = rsLogin.getString("Harga_Tembaga");
                String sharga_plastic = rsLogin.getString("Harga_Plastic");
                String sharga_kaca = rsLogin.getString("Harga_Kaca");
                Dashboard_Admin c= new Dashboard_Admin();
                c.tfinbesi.setText(sharga_besi);
                c.tfintembaga.setText(sharga_tembaga);
                c.tfinplastic.setText(sharga_plastic);
                c.tfinkaca.setText(sharga_kaca);
                c.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "PIN yang anda masukan salah");
                kosong();
                
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_pfpinActionPerformed

    private void tfnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaKeyTyped

    private void tfregist_nohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfregist_nohpKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();

        if(!(Character.isDigit(enter))){

            evt.consume();
        }
    }//GEN-LAST:event_tfregist_nohpKeyTyped

    private void jlnamaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlnamaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlnamaAncestorAdded

    private void tfregist_nohpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfregist_nohpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfregist_nohpKeyPressed

    private void tfregist_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfregist_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfregist_nohpActionPerformed

    private void tfregist_nohpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfregist_nohpKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select Nama from member where No_Handphone = '" + tfregist_nohp.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_sampah = hasil.getString("Nama");
                jlnama.setText(stotal_sampah);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tfregist_nohpKeyReleased

    private void harga_besiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_harga_besiAncestorAdded
        // TODO add your handling code here:
        try {
            String sql = "select Harga_Besi from admin ";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_sampah = hasil.getString("Harga_Besi");
                harga_besi.setText(stotal_sampah);
            }
            } catch (SQLException e) {
        }
    }//GEN-LAST:event_harga_besiAncestorAdded

    private void harga_tembagaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_harga_tembagaAncestorAdded
        // TODO add your handling code here:
        try {
            String sql = "select Harga_Tembaga from admin ";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_sampah = hasil.getString("Harga_Tembaga");
                harga_tembaga.setText(stotal_sampah);
            }
            } catch (SQLException e) {
        }
    }//GEN-LAST:event_harga_tembagaAncestorAdded

    private void harga_plasticAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_harga_plasticAncestorAdded
        // TODO add your handling code here:
        try {
            String sql = "select Harga_Plastic from admin ";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_sampah = hasil.getString("Harga_Plastic");
                harga_plastic.setText(stotal_sampah);
            }
            } catch (SQLException e) {
        }
    }//GEN-LAST:event_harga_plasticAncestorAdded

    private void harga_kacaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_harga_kacaAncestorAdded
        // TODO add your handling code here:
        try {
            String sql = "select Harga_Kaca from admin ";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String stotal_sampah = hasil.getString("Harga_Kaca");
                harga_kaca.setText(stotal_sampah);
            }
            } catch (SQLException e) {
        }
    }//GEN-LAST:event_harga_kacaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Brokers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Brokers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Brokers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Brokers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Brokers().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btsubmit_broker;
    private javax.swing.JComboBox<String> cbjenis_sampah;
    private javax.swing.JComboBox<String> cbverif;
    public static javax.swing.JLabel harga_besi;
    public static javax.swing.JLabel harga_kaca;
    public static javax.swing.JLabel harga_plastic;
    public static javax.swing.JLabel harga_tembaga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlnama;
    private javax.swing.JLabel jlsaldo;
    private javax.swing.JLabel jlsaldo2;
    private javax.swing.JLabel jltanggal;
    private javax.swing.JLabel logo_regist;
    private javax.swing.JPasswordField pfbrokers_pass;
    private javax.swing.JPasswordField pfpin;
    private javax.swing.JTable tabelout;
    private javax.swing.JTextArea tbrokers_alamat;
    private javax.swing.JTextField tfberat_sampah;
    private javax.swing.JTextField tfberita;
    private javax.swing.JTextField tfbrokers_nama;
    private javax.swing.JTextField tfbrokers_user;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfregist_nohp;
    private javax.swing.JTextField tfsaldo;
    private javax.swing.JTextField tftanggal;
    // End of variables declaration//GEN-END:variables

}
