/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan_Menu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;

/**
 *
 * @author user
 */
public class FormLogin extends javax.swing.JFrame {
    private Connection koneksi;
    private New_ConnectDB conn = new New_ConnectDB();

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setLocationRelativeTo(this);
    }
    protected void kosong() {
        tflogin_user.setText("");
        pflogin_pass.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tflogin_user = new javax.swing.JTextField();
        pflogin_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_Menu/logoLogin.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 120, 210, 250);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 245, 90, 21);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(640, 205, 90, 21);

        tflogin_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tflogin_userKeyPressed(evt);
            }
        });
        jPanel1.add(tflogin_user);
        tflogin_user.setBounds(730, 200, 160, 30);

        pflogin_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pflogin_passActionPerformed(evt);
            }
        });
        pflogin_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pflogin_passKeyPressed(evt);
            }
        });
        jPanel1.add(pflogin_pass);
        pflogin_pass.setBounds(730, 240, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("About");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(660, 323, 80, 30);

        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(750, 323, 81, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(840, 323, 60, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Forget my password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 280, 120, 14);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("LOGIN BROKER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(700, 150, 160, 26);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan_Menu/LoginFormLogo.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 970, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new About().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new FormLoginUtama().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pflogin_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pflogin_passKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            conn.connect();
            try {
                String sql = "select * from admin where Username = '" + tflogin_user.getText() + "' and Password = '" + pflogin_pass.getText() + "'";
                Statement stat = conn.connect().createStatement();
                ResultSet rsLogin = stat.executeQuery(sql);

                rsLogin.next();
                rsLogin.last(); //mengecek jumlah baris pada hasil query
                if (rsLogin.getRow()==1){
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
                    dispose();
                    //new Dashboard_Brokers().setVisible(true); //<-- BILA MAU DIARAHKAN KE Frame Menu Utama
                    String sharga_besi = rsLogin.getString("Harga_Besi");
                    String sharga_tembaga = rsLogin.getString("Harga_Tembaga");
                    String sharga_plastic = rsLogin.getString("Harga_Plastic");
                    String sharga_kaca = rsLogin.getString("Harga_Kaca");
                    Dashboard_Brokers b= new Dashboard_Brokers();
                    b.harga_besi.setText(sharga_besi);
                    b.harga_tembaga.setText(sharga_tembaga);
                    b.harga_plastic.setText(sharga_plastic);
                    b.harga_kaca.setText(sharga_kaca);
                    b.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf, Username / Password anda salah!");
                    kosong();
                    tflogin_user.requestFocus();
                }
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_pflogin_passKeyPressed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        conn.connect();
        try {
            String sql = "select * from admin where Username = '" + tflogin_user.getText() + "' and Password = '" + pflogin_pass.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                dispose();
                //new Dashboard_Brokers().setVisible(true); //<-- BILA MAU DIARAHKAN KE Frame Menu Utama
                String sharga_besi = rsLogin.getString("Harga_Besi");
                String sharga_tembaga = rsLogin.getString("Harga_Tembaga");
                String sharga_plastic = rsLogin.getString("Harga_Plastic");
                String sharga_kaca = rsLogin.getString("Harga_Kaca");
                Dashboard_Brokers b= new Dashboard_Brokers();
                b.harga_besi.setText(sharga_besi);
                b.harga_tembaga.setText(sharga_tembaga);
                b.harga_plastic.setText(sharga_plastic);
                b.harga_kaca.setText(sharga_kaca);
                b.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Username / Password anda salah!");
                kosong();
                tflogin_user.requestFocus();
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void pflogin_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pflogin_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pflogin_passActionPerformed

    private void tflogin_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tflogin_userKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            pflogin_pass.requestFocus();
        }
    }//GEN-LAST:event_tflogin_userKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pflogin_pass;
    private javax.swing.JTextField tflogin_user;
    // End of variables declaration//GEN-END:variables

    
}
